---
  title: Tech Knights
  url: ''
  production_url: 'http://techknights.org/'
  author: The Tech Knights Team
  email: team@knighthacks.org
  description: Giving people a space to learn and do things theyâ€™ve never done before
  socialLinks:
    facebook: 'https://www.facebook.com/groups/knighthacksclub/'
    twitter: 'https://twitter.com/techknightsucf'
    github: 'https://github.com/knighthacks'
    instagram: 'https://instagram.com/knighthacks/'
  eventDisplayLimit: 4
  workshopDisplayLimit: 4
  events:
    -
      name: "Glorious PC Building Workshop"
      date: 4/18/2017
      time: 7:30pm
      url: "https://docs.google.com/presentation/d/1u0I-kQArwB0fkCf1ZaqlJbc90xti9wutXXJXnDhMF1A/edit?usp=sharing"
      notice: "NEW"

  workshops:
    -
      name: "Get Swifty! && Officer Elections"
      date: 4/11/2017
      time: 7:30pm
      url: "https://docs.google.com/presentation/d/1QNW6R_tjGJf7_eXCuZB7OZHodwc6QytoX-IF0Cepmh0/edit?usp=sharing"
      notice: none
    -
      name: "Pizzzzzzzzaaaa"
      date: 4/4/2017
      time: 7:30pm
      url: "https://www.facebook.com/events/614350965433320/"
      notice: none
    -
      name: "Adventures in Functional Programming"
      date: 3/31/2017
      time: 6:20pm
      url: "/workshops/functional"
      notice: none
    -
      name: "Alexa Skill Workshop"
      date: 2/24/2017
      time: 6:20pm
      url: "https://www.facebook.com/events/201285553686846/"
    -
      name: "Welcome to Python"
      date: 2/10/2017
      time: 6:20PM
      url: "https://www.facebook.com/events/246693375785331/"
    -
      name: "We've Got Your Hack"
      date: 2/3/2017
      time: 6:20 PM
      url: 'https://docs.google.com/presentation/d/1H_j1CCL817seTw9pL7RysexfP-uBeAoidjzFTVUUVHs/edit?usp=sharing'
    -
      name: 'Welcome to Bash!'
      date: 1/27/2017
      time: 6:20 PM
      url: '/workshops/bash'
    -
      name: 'Continuous Integration with REV'
      date: 11/18/2016
      time: 6:10 PM
      url: 'https://www.facebook.com/events/129890784155709/'
    -
      name: 'Demystifying the Cloud'
      date: 11/11/2016
      time: 6:10 PM
      url: 'https://www.facebook.com/events/886841571452433/'
    -
      name: 'Introduction to Android Development'
      date: 11/4/2016
      time: 6:10 PM
      url: 'http://techknights.org/workshops/intro-android-workshop/'
    -
      name: 'Hacktoberfest Social'
      date: 10/28/2016
      time: 6:10 PM
      url: 'https://www.facebook.com/events/664233557075538/'
    -
      name: 'Money, Investing, Job Offers, and You: Finances as a Developer'
      date: 10/21/2016
      time: 6:10 PM
      url: 'https://slides.com/stevenpetryk/pf'
    -
      name: 'What is a Hackathon Anyway?'
      date: 9/30/2016
      time: 6:10 PM
      url: 'https://www.facebook.com/events/1227352160620537/'
    -
      name: 'Interview Prep'
      date: 9/23/2016
      time: 6:10 PM
      url: 'https://www.facebook.com/events/153380668447638/'
    -
      name: 'State Farm Lightning Talks'
      date: 9/14/2016
      time: 6:10 PM
      url: 'https://www.facebook.com/events/908378785934242/'
    -
      name: 'SQL Workshop'
      date: 9/9/2016
      time: 6:10 PM
      url: '/workshops/sql'
    -
      name: 'Initial Commit'
      date: 9/2/2016
      time: 6:10 PM
      url: 'https://www.facebook.com/events/1762713793946591/'
    -
      name: 'Django Workshop'
      date: 4/22/2016
      time: 6:15 PM
      url: 'https://github.com/thedarkestknight/Gluebin/blob/master/WORKSHOP.md'
    -
      name: 'IoT Workshop'
      date: 4/15/2016
      time: 6:15 PM
      url: '/workshops/iot'
    -
      name: 'Web Security Slides'
      date: 4/08/2016
      time: 6:15 PM
      url: 'https://docs.google.com/presentation/d/1Zvd1EN1-SPl0Xgj74GS3jh6vVSVufNYMV9S3GltNiCk/edit#slide=id.p'
    -
      name: 'Chess Demo Files'
      date: 4/01/2016
      time: 6:15 PM
      url: '/ChessDemo.zip'
    -
      name: 'Intro to Angular.js'
      date: 3/25/2016
      time: 6:15 PM
      url: '/workshops/angular'
    -
      name: 'Intro to React.js'
      date: 3/18/2016
      time: 6:15 PM
      url: '/workshops/react'
    -
      name: 'JavaScript & ES6'
      date: 2/19/2016
      time: 6:15 PM
      url: '/workshops/javascript'
    -
      name: 'Dev Environments and Tools'
      date: 2/12/2016
      time: 6:15 PM
      url: '/workshops/dev-environments'
    -
      name: 'Node.js Twitterbot Workshop'
      date: 2/5/2016
      time: 6:15 PM
      url: '/workshops/nodejs-twitterbot'
    -
      name: 'Flask Web Development (Python)'
      date: 1/29/2016
      time: 6:15 PM
      url: '/workshops/flask-workshop'
    -
      name: 'Front End Web Development'
      date: 11/13/2015
      time: 6:15 PM
      url: '/workshops/frontend-web-development'
    -
      name: 'Introduction to Web Development'
      date: 10/30/2015
      time: 6:15 PM
      url: '/workshops/intro-web-development'
    -
      name: 'Introduction to Android'
      date: 10/23/2015
      time: 6:15 PM
      url: '/workshops/intro-android-workshop'
    -
      name: 'Introduction to Vim'
      date: 10/16/2015
      time: 6:15 PM
      url: '/workshops/vim-workshop'
    -
      name: 'Advanced Git Workshop'
      date: 10/9/2015
      time: 6:15 PM
      url: '/workshops/advanced-git-workshop'
    -
      name: 'Set up a free cloud server with Azure'
      date: 9/25/2015
      time: 6:15 PM
      url: '/workshops/azure'
    -
      name: '`git` Workshop'
      date: 9/18/2015
      time: 6:15 PM
      url: '/workshops/git-workshop'
    -
      name: 'Using GitHub effectively (Slides)'
      date: 9/17/2015
      time: 7:30 PM
      url: 'https://docs.google.com/presentation/d/1hbq1V4rirMkDv0saQVP-cqzi0SJr04xF-DW1FhbDrMk/edit?usp=sharing'
    -
      name: 'Command Line Workshop'
      date: 9/11/2015
      time: 6:15 PM
      url: '/workshops/command-line'
